<a href="https://colab.research.google.com/github/aaabbbdddeee/MAT_422/blob/main/Assignment11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Neural Networks**

Neural networks simulate the workings of the human brain using layers of interconnected nodes. They learn by adjusting weights (w) and biases (b) to predict outputs (ŷ) from inputs (x), utilizing an activation function (σ) to introduce non-linearity. The process of training involves:

Outputs are calculated as ŷ = σ(w1x1 + w2x2 + b), where w1, w2 are weights, x1, x2 are inputs, and b is the bias. This is extended to complex networks with many layers, using matrices for weights (W) and biases (b) for efficiency.

In [2]:
import tensorflow as tf

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.09432407,  0.00582404, -1.196496  , -0.6683928 , -1.1084404 ,
        -1.435814  ,  0.1227283 , -0.32034197, -0.21727523,  0.7355907 ]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.11309104, 0.12500343, 0.03756306, 0.06369616, 0.0410207 ,
        0.02956831, 0.14050533, 0.09021315, 0.10000717, 0.25933167]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

3.5210524

In [12]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2984 - accuracy: 0.9135
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1468 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.1069 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0880 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0756 - accuracy: 0.9757


In [14]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0660 - accuracy: 0.9789 - 1s/epoch - 4ms/step


[0.06598321348428726, 0.9789000153541565]

In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.55520866e-07, 5.51367663e-09, 2.65564067e-05, 1.87117184e-04,
        1.16173095e-11, 1.90204261e-07, 1.48565188e-12, 9.99764502e-01,
        1.25213921e-06, 2.01855037e-05],
       [3.73133382e-08, 8.10380268e-04, 9.99187052e-01, 2.58813930e-06,
        8.99595974e-17, 7.89981680e-09, 7.28191507e-09, 4.71689609e-14,
        1.51645674e-09, 1.69713374e-16],
       [7.68697745e-08, 9.99570906e-01, 2.96125618e-05, 7.08992138e-06,
        1.25351489e-05, 1.07191618e-05, 1.93240467e-05, 2.30875827e-04,
        1.17555246e-04, 1.26958753e-06],
       [9.99897599e-01, 1.12373939e-07, 5.69502809e-05, 6.76807446e-08,
        2.16258763e-06, 4.93274774e-06, 1.91501222e-05, 1.38305531e-05,
        4.25887464e-07, 4.78305356e-06],
       [7.49646733e-06, 4.24993063e-09, 1.04684368e-05, 1.92755749e-08,
        9.96633589e-01, 1.66633208e-06, 2.52797986e-06, 1.92176129e-04,
        4.50147610e-07, 3.15167313e-03]], dtype=float32)>